<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>preview</LangVersion> <!-- https://github.com/dotnet/fsharp/issues/17501 -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<OutputPath>..\..\bin\Debug\</OutputPath>
		<NoWarn>0686</NoWarn>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<OutputPath>..\..\bin\Release\</OutputPath>
		<NoWarn>0686</NoWarn>
	</PropertyGroup>
  <ItemGroup>
    <None Include="Annotations\annotation_1.ann" />
	<None Include="Annotations\annotation_1_latlon.json" />
	<None Include="Annotations\annotation_1_xyz.json" />
	<None Include="Annotations\annotation_1_xyz_latlon.json" />
    <Compile Include="GeoJsonExportTest.fs" />
    <Compile Include="HeraSpiceTests.fs" />
    <Compile Include="QueriesDSL.fs" />
    <None Include="Playground.fsx" />
    <None Include="RemoteApi.rest" />
    <None Include="paket.references" />
    <Compile Include="BaseTests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PRo3D.Base\PRo3D.Base.fsproj" />
    <ProjectReference Include="..\PRo3D.Core\PRo3D.Core.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Thoth.Json.Net" Version="12.0.0" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>