// Capture the documentation screenshot set for docs/MultiImageProjection.md.
//
// Run: npx tsx src/probe-docs-shots.ts        (needs PRO3D_TEST_DATA + PRO3D_SPICE_KERNELS)
//
// The previous version of this probe hard-coded `HERA_AFC_*_COP.png` names from a private
// COP folder, so nobody could regenerate the doc images from the repo, and it launched the
// raw projection-test scene with `launchPro3d()`. That scene has no GIS body/frame binding
// and the probe never touched Transfer Function or Orientation Source, so the committed
// screenshots showed a false-coloured body, a "conversion failed (set planet)" overlay and
// a projection offset against the silhouette. This version uses the AFC images that ship in
// PRo3D.Resources.TestData and sets the scene up the way docs/MultiImageProjection.md says
// to, so the images can be regenerated by anyone.
//
// The story the shots tell: Dimorphos carries its DRACO texture; the AFC images were
// simulated from that same model with `pro3d-tool simulate-image`, so a correctly set up
// projection lands on it exactly -- sliding the opacity blends between two things that
// coincide, with no ghosting. A second image then covers terrain the first one never saw.
import { chromium, Page } from "@playwright/test";
import { launchPro3d, fixture, sceneFor, config, surfaceShadersReady } from "./pro3d";
import { bodyCoverage, litFraction, streamLive, diffPng } from "./image";
import * as fs from "fs";
import * as path from "path";

const outDir = path.resolve(__dirname, "..", "..", "docs", "images");
const work = path.resolve(__dirname, "..", "artifacts", "docs-shots");

/** the two AFC frames, lowest and highest sub-spacecraft latitude of the four in the set,
 *  so the second one covers terrain the first misses */
const imgA = process.env.PRO3D_DOC_IMAGE_A ?? "AFC1_DRACO2_20270321_140000.png";
const imgB = process.env.PRO3D_DOC_IMAGE_B ?? "AFC1_DRACO2_20270321_230000.png";

function splashFraction(buf: Buffer): number {
    const { PNG } = require("pngjs");
    const img = PNG.sync.read(buf);
    let hits = 0, total = 0;
    for (let y = Math.floor(img.height * 0.3); y < Math.floor(img.height * 0.8); y++)
        for (let x = Math.floor(img.width * 0.3); x < Math.floor(img.width * 0.75); x++) {
            const i = (img.width * y + x) * 4;
            const r = img.data[i], g = img.data[i + 1], b = img.data[i + 2];
            total++;
            if (r > 150 && g > 170 && b < 130 && g > b + 60) hits++;
        }
    return total === 0 ? 0 : hits / total;
}

/** the surface on screen (not the AARDVARK splash), then two near-identical frames */
async function settled(page: Page, name: string): Promise<Buffer> {
    const started = Date.now();
    const loading = (b: Buffer) =>
        !streamLive(b) || litFraction(b) < 0.003 || splashFraction(b) > 0.002;
    let shot = await page.screenshot();
    while (loading(shot) && Date.now() - started < 420_000) {
        await page.waitForTimeout(3000);
        shot = await page.screenshot();
    }
    let prev = shot;
    for (let i = 0; i < 40; i++) {
        await page.waitForTimeout(1000);
        const cur = await page.screenshot();
        if (diffPng(prev, cur).changedFraction < 0.001) { prev = cur; break; }
        prev = cur;
    }
    fs.writeFileSync(path.join(work, name), prev);
    if (name.startsWith("multiProjection-")) fs.writeFileSync(path.join(outDir, name), prev);
    return prev;
}

const ev = (js: string) => js; // evaluate bodies are strings under tsx (README)

async function clickRowIcon(gis: Page, name: string, icon: string) {
    const r = await gis.evaluate(
        `(function(){
            var matches = Array.from(document.querySelectorAll("*")).filter(function(e){
                return (e.textContent || "").trim() === ${JSON.stringify(name)}; });
            var deepest = matches.filter(function(e){
                return !Array.from(e.children).some(function(c){ return matches.indexOf(c) >= 0; }); });
            if (deepest.length === 0) return "row not found";
            var el = deepest[0];
            while (el) {
                var row = el.nextElementSibling;
                var box = row ? row.querySelector("i.${icon}.icon") : null;
                if (box) { box.click(); return "clicked"; }
                el = el.parentElement;
            }
            return "no i.${icon}.icon in row";
        })()`
    );
    if (r !== "clicked") throw new Error(`${icon} on ${name}: ${r}`);
}

async function hoverRow(gis: Page, name: string, type: string) {
    await gis.evaluate(
        `(function(){
            var matches = Array.from(document.querySelectorAll("*")).filter(function(e){
                return (e.textContent || "").trim() === ${JSON.stringify(name)}; });
            var deepest = matches.filter(function(e){
                return !Array.from(e.children).some(function(c){ return matches.indexOf(c) >= 0; }); });
            var el = deepest[0];
            while (el && !(el.style && el.style.border.length > 0)) el = el.parentElement;
            if (el) el.dispatchEvent(new MouseEvent(${JSON.stringify(type)}, { bubbles: false }));
        })()`
    );
}

async function selectBeside(gis: Page, label: string, option: string) {
    const r = await gis.evaluate(
        `(function(){
            var el = Array.from(document.querySelectorAll("*")).find(function(e){
                return (e.textContent || "").trim() === ${JSON.stringify(label)}; });
            var sel = el && el.parentElement ? el.parentElement.querySelector("select") : null;
            if (!sel) return "no select beside ${label}";
            var opt = Array.from(sel.options).find(function(x){
                return x.textContent.trim() === ${JSON.stringify(option)}; });
            if (!opt) return "no option";
            sel.value = opt.value;
            sel.dispatchEvent(new Event("change", { bubbles: true }));
            return "ok";
        })()`
    );
    if (r !== "ok") throw new Error(`${label} -> ${option}: ${r}`);
}

/** the Image Opacity slider: an <input type=range> driven by the native value setter */
async function setOpacity(gis: Page, value: number) {
    const r = await gis.evaluate(
        `(function(){
            var inp = Array.from(document.querySelectorAll('input[type=range]'))
                .filter(function(i){ return i.max === "1.000000" || i.max === "1"; })[0];
            if (!inp) return "no opacity slider";
            var set = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, "value").set;
            set.call(inp, String(${value}));
            inp.dispatchEvent(new Event("input", { bubbles: true }));
            inp.dispatchEvent(new Event("change", { bubbles: true }));
            return "set:" + inp.value;
        })()`
    );
    console.log(`  opacity -> ${value}: ${r}`);
}

(async () => {
    fs.mkdirSync(outDir, { recursive: true });
    fs.mkdirSync(work, { recursive: true });

    // the scene docs/MultiImageProjection.md §1 asks for: body + frame bound, so the
    // projection has a frame to land in, and a normal 60 deg camera rather than the AFC lens
    const scene = path.join(work, "docs-shots.pro3d");
    sceneFor(fixture.sceneTemplate, fixture.opc, scene);
    const d = JSON.parse(fs.readFileSync(scene, "utf-8"));
    // These four lines mirror the known-good workshop scene
    // (pro3ddata/HERA/workshop3/Projection Test Data/AFC_Dimorphos_v2_2027-03-21/ProjectionTest.pro3d),
    // whose OPC and AFC images are byte-identical to the test repo's -- only the scene
    // settings differed. Notably `planet` is set explicitly rather than left at None for the
    // scene-body sync to infer, the camera source is Didymos, and the epoch is the one the
    // second image was taken at.
    d.gisApp.gisSurfaces = [];
    d.gisApp.defaultObservationInfo.observer = { EntitySpiceName: "Dimorphos" };
    d.gisApp.defaultObservationInfo.referenceFrame = { FrameSpiceName: "DIMORPHOS_FIXED" };
    d.gisApp.defaultObservationInfo.target = { EntitySpiceName: "Didymos" };
    d.gisApp.defaultObservationInfo.time = "2027-03-21T23:00:00.0000000Z";
    d.referenceSystem.planet = 9; // Planet.Dimorphos
    d.navigationMode = 0;
    // PRo3D's normal 60 deg camera. Fly-to frames the instrument FOOTPRINT, which at an 8 km
    // range is several times wider than the 160 m body, so flying to an image leaves the body
    // a speck whatever the focal length is. The hero shots therefore place the camera along
    // the image's own viewing direction instead (below); fly-to gets its own screenshot.
    if (d.config?.frustumModel) d.config.frustumModel.focal = Number(process.env.PRO3D_DOC_FOCAL ?? 10.25);
    // The camera is set by fly-to below, not here: the sidecar's TRG_POS is not expressed
    // in the body-fixed frame, so a longitude derived from it lands on the wrong side of a
    // rotating body -- which is exactly how the previous doc images got their smearing.
    fs.writeFileSync(scene, JSON.stringify(d, null, 2));

    const app = await launchPro3d(scene);
    const browser = await chromium.launch();
    const context = await browser.newContext();

    let render = await context.newPage();
    await render.setViewportSize({ width: 1280, height: 800 });
    await render.goto(app.url + "?page=render");
    await render.waitForSelector("img.rendercontrol", { timeout: 60_000 });
    await surfaceShadersReady(render);

    let gis = await context.newPage();
    await gis.setViewportSize({ width: 1100, height: 1000 });
    await gis.goto(app.url + "?page=gis");
    await gis.waitForLoadState("networkidle");
    await gis.locator("text=Projected Images").first().click();
    await gis.locator("text=Import Directory").first().waitFor({ timeout: 60_000 });
    const dir = config.imageDir.replace(/\\/g, "/");
    await gis.evaluate(
        `(function(){ window.aardvark = window.aardvark || {};
           window.aardvark.dialog = { showOpenDialog: function(){
               return Promise.resolve({ canceled: false, filePaths: [${JSON.stringify(dir)}] }); } }; })()`
    );
    await gis.locator("text=Import Directory").first().click();
    await gis.locator(`text=${imgA}`).first().waitFor({ timeout: 120_000 });

    // settings the doc prescribes: the sidecar pose, and the image's own pixels
    await gis.locator("text=Projection Settings").first().click();
    await gis.waitForTimeout(1200);
    await selectBeside(gis, "Orientation Source:", "MbiBased");
    const tf = await gis.evaluate(
        `(function(){
            var el = Array.from(document.querySelectorAll("*")).find(function(e){
                return (e.textContent || "").trim() === "Transfer Function:"; });
            var box = el && el.parentElement ? el.parentElement.querySelector("i") : null;
            if (!box) return "checkbox not found";
            box.click();
            return "clicked";
        })()`
    );
    console.log("transfer function ->", tf);
    await gis.waitForTimeout(1500);

    // Fly to the image so PRo3D computes the instrument's viewpoint for us (the sidecar's
    // TRG_POS is not body-fixed, so deriving it by hand lands on the wrong side of a
    // rotating body), then read the camera position back out of the HUD.
    //
    // Fly-to frames the instrument FOOTPRINT, which at an 8 km range is far wider than the
    // 160 m body, so the body comes out a speck. Scrolling does not fix it: the wheel moves
    // the camera AWAY here whichever sign it is given (-300 -> 77 km, +300 -> 2.5 km). So
    // phase 2 below relaunches with the same viewing direction at a chosen distance.
    await clickRowIcon(gis, imgA, "location");
    await render.waitForTimeout(9000);
    const hud = async () => (await render.evaluate(
        `(document.querySelector('table') || {}).innerText || ''`)) as string;
    const posText = /Position:\s*\[([^\]]+)\]/.exec(await hud());
    if (!posText) throw new Error("could not read the camera position from the HUD");
    const flyPos = posText[1].split(",").map((x) => Number(x.trim().replace(/\./g, "").replace(",", ".")));
    console.log("fly-to camera position:", flyPos.map((c) => c.toFixed(1)).join(", "));
    await context.close();
    await browser.close();
    await app.stop();

    // ---- phase 2: same direction, close enough that the body fills the frame ----------
    const dist = Number(process.env.PRO3D_DOC_DIST ?? 400);
    const n = Math.hypot(flyPos[0], flyPos[1], flyPos[2]);
    const pos = flyPos.map((c) => (c / n) * dist);
    const norm = (v: number[]) => { const m = Math.hypot(v[0], v[1], v[2]); return v.map((c) => c / m); };
    const fwd = norm(pos.map((c) => -c));
    const sky = [0, 0, 1];
    const dt = sky[0] * fwd[0] + sky[1] * fwd[1] + sky[2] * fwd[2];
    const up = norm(sky.map((c, i) => c - dt * fwd[i]));
    const right = norm([
        fwd[1] * up[2] - fwd[2] * up[1],
        fwd[2] * up[0] - fwd[0] * up[2],
        fwd[0] * up[1] - fwd[1] * up[0],
    ]);
    const v3 = (v: number[]) => JSON.stringify(v.map((c) => Number(c.toFixed(9))));
    const d2 = JSON.parse(fs.readFileSync(scene, "utf-8"));
    d2.cameraView.view = [v3(sky), v3(pos), v3(fwd), v3(up), v3(right)];
    const scene2 = path.join(work, "docs-shots-framed.pro3d");
    d2.scenePath = scene2;
    fs.writeFileSync(scene2, JSON.stringify(d2, null, 2));

    const app2 = await launchPro3d(scene2);
    const browser2 = await chromium.launch();
    const context2 = await browser2.newContext();
    render = await context2.newPage();
    await render.setViewportSize({ width: 1280, height: 800 });
    await render.goto(app2.url + "?page=render");
    await render.waitForSelector("img.rendercontrol", { timeout: 60_000 });
    await surfaceShadersReady(render);
    gis = await context2.newPage();
    await gis.setViewportSize({ width: 1100, height: 1000 });
    await gis.goto(app2.url + "?page=gis");
    await gis.waitForLoadState("networkidle");
    await gis.locator("text=Projected Images").first().click();
    await gis.locator("text=Import Directory").first().waitFor({ timeout: 60_000 });
    await gis.evaluate(
        `(function(){ window.aardvark = window.aardvark || {};
           window.aardvark.dialog = { showOpenDialog: function(){
               return Promise.resolve({ canceled: false, filePaths: [${JSON.stringify(dir)}] }); } }; })()`
    );
    await gis.locator("text=Import Directory").first().click();
    await gis.locator(`text=${imgA}`).first().waitFor({ timeout: 120_000 });
    await gis.locator("text=Projection Settings").first().click();
    await gis.waitForTimeout(1200);
    await selectBeside(gis, "Orientation Source:", "MbiBased");
    await gis.evaluate(
        `(function(){
            var el = Array.from(document.querySelectorAll("*")).find(function(e){
                return (e.textContent || "").trim() === "Transfer Function:"; });
            var box = el && el.parentElement ? el.parentElement.querySelector("i") : null;
            if (box) box.click();
            return "ok";
        })()`
    );
    await gis.waitForTimeout(1500);
    console.log("phase 2 altitude:", /Altitude:\s*([0-9.,]+)/.exec(await hud())?.[1]);

    // 1: the body as it ships -- its own DRACO texture, nothing projected yet
    const base = await settled(render, "multiProjection-surface.png");
    console.log("baseline lit:", litFraction(base).toFixed(4));

    // 2: hover preview + footprint + frustum
    await hoverRow(gis, imgA, "mouseenter");
    await render.waitForTimeout(5000);
    await render.screenshot({ path: path.join(outDir, "multiProjection-hover.png") });
    await hoverRow(gis, imgA, "mouseleave");
    await render.waitForTimeout(2000);

    // 3: one image projected, at full opacity. Simulated from this very model, so it should
    //    coincide with the texture underneath rather than fight it.
    await clickRowIcon(gis, imgA, "plus");
    await gis.waitForTimeout(2000);
    const oneUp = await settled(render, "multiProjection-stack.png");
    const covA = bodyCoverage(base, oneUp);
    console.log(`one image: covered=${covA.coveredFraction.toFixed(3)} spilled=${covA.spilledFraction.toFixed(3)}`);

    // 4: the opacity sweep -- the doc's proof that the projection registers
    for (const [v, name] of [[0, "multiProjection-opacity-000.png"], [0.5, "multiProjection-opacity-050.png"], [1, "multiProjection-opacity-100.png"]] as [number, string][]) {
        await setOpacity(gis, v);
        await render.waitForTimeout(4000);
        const shot = await settled(render, name);
        console.log(`  opacity ${v}: diff vs baseline = ${diffPng(base, shot).changedFraction.toFixed(4)}`);
    }
    await setOpacity(gis, 1);
    await render.waitForTimeout(3000);

    // 5: the coverage view, taken here because fly-to later re-frames the camera a
    //    kilometre out and the body becomes a speck.
    await selectBeside(gis, "Visibility:", "RelativeCount");
    await render.waitForTimeout(6000);
    await settled(render, "multiProjection-coverage.png");
    await selectBeside(gis, "Visibility:", "Off");
    await render.waitForTimeout(4000);

    // 5: orbit to the far side. Dimorphos is tidally locked with a ~11.9 h period, so
    //    between the 14:00 and 23:00 frames it turns roughly 270 deg: in BODY-FIXED terms
    //    the two images see opposite hemispheres. From imgA's viewpoint the second image
    //    therefore adds nothing (measured: +0.003 coverage) -- you have to go and look.
    //
    //    ArcBall + "C" pivots the orbit on the body centre (Viewer.fs:1824 ->
    //    ArcBallController.Message.Pick V3d.Zero), which is what keeps the body framed
    //    while the camera swings around it.
    const vp2 = render.viewportSize() ?? { width: 1280, height: 800 };
    const cx = Math.round(vp2.width / 2), cy = Math.round(vp2.height / 2);
    await render.evaluate(
        `(function(){
            var t = Array.from(document.querySelectorAll('.pro3d-tool')).find(function(e){
                return (e.getAttribute('title') || '').indexOf('ArcBall') === 0; });
            if (!t) return 'no ArcBall button';
            t.click();
            return 'clicked';
        })()`
    ).then((r) => console.log("ArcBall:", r));
    await render.waitForTimeout(1500);
    await render.mouse.move(cx, cy);          // the control focuses itself on mouseenter
    await render.waitForTimeout(500);
    await render.keyboard.press("c");         // pivot -> body centre
    await render.waitForTimeout(1500);

    const num = (s: string) => Number(s.replace(/\./g, "").replace(",", "."));
    const lonNow = async () => {
        const t = (await render.evaluate(`(document.querySelector('table') || {}).innerText || ''`)) as string;
        const m = /Longitude:\s*([0-9.,]+)/.exec(t);
        return m ? num(m[1]) : NaN;
    };
    const drag = async (dx: number) => {
        await render.mouse.move(cx, cy);
        await render.mouse.down();
        for (let i = 1; i <= 10; i++) await render.mouse.move(cx + (dx * i) / 10, cy);
        await render.mouse.up();
        await render.waitForTimeout(600);
    };
    const lon0 = await lonNow();
    let turned = 0;
    let stuck = 0;
    for (let i = 0; i < 40 && turned < 165; i++) {
        const before = await lonNow();
        await drag(220);
        const cur = await lonNow();
        // signed shortest angular difference, in [-180, 180]
        turned = Math.abs((((cur - lon0) % 360) + 540) % 360 - 180);
        if (Math.abs((((cur - before) % 360) + 540) % 360 - 180) < 0.5) stuck++; else stuck = 0;
        if (stuck >= 3) throw new Error(`the orbit drag is not moving the camera (longitude stuck at ${cur})`);
        if (i % 4 === 0) console.log(`  orbit step ${i}: lon ${cur.toFixed(1)}, turned ${turned.toFixed(0)} deg`);
    }
    console.log(`orbited ${turned.toFixed(0)} deg: longitude ${lon0.toFixed(1)} -> ${(await lonNow()).toFixed(1)}`);
    if (turned < 120) throw new Error(`orbit only reached ${turned.toFixed(0)} deg; the far-side shots would not show the far side`);
    const farOne = await settled(render, "farside-one-image.png");

    // 6: the second image, which is the one that saw THIS hemisphere
    await clickRowIcon(gis, imgB, "plus");
    await gis.waitForTimeout(2000);
    const farTwo = await settled(render, "farside-two-images.png");
    const covFar = bodyCoverage(farOne, farTwo);
    console.log(`far side: the second image covers ${covFar.coveredFraction.toFixed(3)} of it (spill ${covFar.spilledFraction.toFixed(3)})`);


    // 7: the panel itself, with a populated stack
    await gis.screenshot({ path: path.join(outDir, "multiProjection-gisTab.png") });

    // 8: fly-to from a STACK row (the same control also sits in every library row)
    const fly = await gis.evaluate(
        `(function(){
            var rows = Array.from(document.querySelectorAll("div")).filter(function(dv){
                return dv.querySelector("i.location.icon") && (dv.textContent || "").trim() === ${JSON.stringify(imgA)}; });
            if (rows.length === 0) return "no stack row";
            rows[rows.length - 1].querySelector("i.location.icon").click();
            return "clicked";
        })()`
    );
    console.log("fly-to:", fly);
    await render.waitForTimeout(9000);
    await settled(render, "multiProjection-flyTo.png");

    console.log("screenshots written to", outDir);
    await browser2.close();
    await app2.stop();
    process.exit(0);
})();
