name: Build

on:
  push:
    paths-ignore:
    - 'README.md'
    - 'docs/'
  pull_request:
    paths-ignore:
    - 'README.md'
    - 'docs/'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-latest, windows-latest, macos-15-intel, macos-15]
            include:
              - os: ubuntu-latest
                run-build: sh ./build.sh
              - os: windows-latest
                run-build: .\build.cmd
              - os: macos-15-intel
                run-build: bash ./build.sh
              - os: macos-15
                run-build: bash ./build.sh
    steps:
    - uses: actions/checkout@v4
    - name: Install Dotnet
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Build
      run: ${{ matrix.run-build }}
